[build]
  base = "client"
  command = "npm install && npm run build && cd ../server && npm install"
  publish = "dist"

[functions]
  directory = "../server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
